TOOLS = [
    "agora test build",
    "atomic search",
    "blue jeans",
    "brainfuse",
    "brainfuse tutoring",
    "chat",
    "codio canvas lti",
    "feedbackfruits - assignment review",
    "feedbackfruits - automated feedback",
    "feedbackfruits - comprehension",
    "feedbackfruits - discussion assignment",
    "feedbackfruits - group member evaluation",
    "feedbackfruits - interactive audio",
    "feedbackfruits - interactive document",
    "feedbackfruits - interactive presentation",
    "feedbackfruits - interactive video",
    "feedbackfruits - peer review",
    "feedbackfruits - self assessment",
    "feedbackfruits - skill review",
    "goreact",
    "gradescope",
    "honorlock",
    "hypothes.is",
    "labarchives",
    "lockdown browser",
    "logoi quick dialogues",
    "mcgraw hill campus",
    "mediasite",
    "mediasite-psom",
    "psom zoom",
    "padlet tool",
    "peerceptiv",
    "penn+box",
    "perusall",
    "piazza",
    "proctoru",
    "proctoru - lti",
    "scorm",
    "scorm",
    "virtual meetings",
    "voicethread",
    "voicethread",
    "youtube",
    "zoom",
    "zoom psom",
    "iseek",
    "iseek search",
]
